name: React CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: build
      run: |
        npm install
        npm run build --prod

    - name: Set UUID
      id: generate-uuid
      uses: filipstefansson/uuid-action@v1

    - name: zipx
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ${{ secrets.TEAM_ID}}@${{ secrets.APP_NAME}}@${{ steps.generate-uuid.outputs.uuid }}.zip build

    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      env:
        FILE: ${{ secrets.TEAM_ID}}@${{ secrets.APP_NAME}}@${{ steps.generate-uuid.outputs.uuid }}.zip
        AWS_REGION: ${{secrets.AWS_REGION}}
        S3_BUCKET: ${{secrets.AWS_BUCKET}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
